// This file was generated by Prisma, and assumes you have installed the following:

import { config } from "dotenv";

// 1) Load env files explicitly (order matters)
config({ path: ".env.local" }); // my Neon vars
config({ path: ".env" }); // optional fallback

import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --env-file=.env.local prisma/seed.js",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
